import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./GlobalRedux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: {
        default: "Accueil | Axel Portfolio",
        template: "%s | Axel Portfolio",
    },
    template: " %s | Axel Portfolio",
    description: "Accueil du portfolio",
    keywords: "accueil, axel raboit, axel, presentation, compétences, projets",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}

/* import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./GlobalRedux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
 */